123/MyProject/src/objects/Agent__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Reg_Date__c</fullName>
        <label>Reg. Date</label>
        <type>Date</type>
    </fields>
    <label>Agent</label>
    <nameField>
        <label>Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

123/MyProject/src/classes/AddAgentCtrl.cls
public class AddAgentCtrl{
    public Agent__c cds{get; set;}
        
    public Agent__c setcds(Agent__c op){
        this.cds=op;
        return cds;
    }
    public AddAgentCtrl(ApexPages.StandardController controller) {
        cds=new Agent__c();
    }

    public pagereference SaveandNew(){
        Agent__c cd = new Agent__c();
        cd.name = cds.name;
        cd.Date_of_Birth__c = cds.Date_of_Birth__c ;
        cd.Gender__c = cds.Gender__c;
        cd.Phone__c = cds.Phone__c;
        cd.Email__c = cds.Email__c;
        cd.Reg_Date__c = cds.Reg_Date__c;
        cd.Address__c = cds.Address__c;

        insert cd;
        
        Pagereference pg = new Pagereference('/apex/AddAgentVF');
        pg.setredirect(true);
        return pg;


    }
    public pageReference save(){
        Agent__c cd = new Agent__c();
        cd.name = cds.name;
        cd.Date_of_Birth__c = cds.Date_of_Birth__c ;
        cd.Gender__c = cds.Gender__c;
        cd.Phone__c = cds.Phone__c;
        cd.Email__c = cds.Email__c;
        cd.Reg_Date__c = cds.Reg_Date__c;
        cd.Address__c = cds.Address__c;
        insert cd;
        pagereference p = new pageReference('/'+cd.id);
        return p;
    
    }
    public PageReference Cancel(){
    
        pageReference g = new pageReference('/apex/IMSVF');
        
        return g;
    }
}