123/MyProject/src/objects/Life_Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Agent_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agent ID</label>
        <referenceTo>Agent__c</referenceTo>
        <relationshipLabel>Life Insurances</relationshipLabel>
        <relationshipName>Life_Insurances</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No_of_Terms__c</fullName>
        <label>No. of Terms</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Policy_Holder_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Policy Holder Name</label>
        <referenceTo>Policy_Holder__c</referenceTo>
        <relationshipLabel>Life Insurances</relationshipLabel>
        <relationshipName>Life_Insurances</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Premium_Amount__c</fullName>
        <label>Premium Amount</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Premium_End_Date__c</fullName>
        <label>Premium End  Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Premium_Start_Date__c</fullName>
        <label>Premium Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Premium_Type__c</fullName>
        <label>Premium Type</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Life Insurance</label>
    <nameField>
        <displayFormat>LIID-{0000}</displayFormat>
        <label>Policy ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Life Insurances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

123/MyProject/src/classes/AddLifeInsurenceCtrl.cls
public class AddLifeInsurenceCtrl {
    public Life_Insurance__c cds{get; set;}
        
    public Life_Insurance__c setcds(Life_Insurance__c op){
        this.cds=op;
        return cds;
    }
    public AddLifeInsurenceCtrl (ApexPages.StandardController controller) {
        cds=new Life_Insurance__c ();
    }

    public pagereference SaveandNew(){
        Life_Insurance__c cd = new Life_Insurance__c();
               
        cd.Policy_Holder_Name__c= cds.Policy_Holder_Name__c;
        cd.Agent_ID__c= cds.Agent_ID__c;
        cd.Premium_Amount__c= cds.Premium_Amount__c;
        cd.No_of_Terms__c= cds.No_of_Terms__c;
        cd.Premium_Type__c= cds.Premium_Type__c;
        cd.Premium_Start_Date__c= cds.Premium_Start_Date__c;
        cd.Premium_End_Date__c= cds.Premium_End_Date__c;

        insert cd;
        
        Pagereference pg = new Pagereference('/apex/AddLifeInsurenceVF');
        pg.setredirect(true);
        return pg;


    }
    public pageReference save(){
        Life_Insurance__c cd = new Life_Insurance__c();
        
                
        cd.Policy_Holder_Name__c= cds.Policy_Holder_Name__c;
        cd.Agent_ID__c= cds.Agent_ID__c;
        cd.Premium_Amount__c= cds.Premium_Amount__c;
        cd.No_of_Terms__c= cds.No_of_Terms__c;
        cd.Premium_Type__c= cds.Premium_Type__c;
        cd.Premium_Start_Date__c= cds.Premium_Start_Date__c;
        cd.Premium_End_Date__c= cds.Premium_End_Date__c;
        
        insert cd;
        pagereference p = new pageReference('/'+cd.id);
        return p;
    
    }
    public PageReference Cancel(){
    
        pageReference g = new pageReference('/apex/IMSVF');
        
        return g;
    }
}