123/MyProject/src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <picklist>
            <picklistValues>
                <fullName>Savings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>NRI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

123/MyProject/src/classes/loanCtrl.cls
public class loanCtrl {

    public loanCtrl(ApexPages.StandardSetController controller) {

    }

    public String lname {set;get;}
    public Decimal lSalary {set;get;}
    public String lacc {set;get;}
    
    loan__c lo;
    
    public pageReference insertloan(){
        lo = new loan__C();
        lo.name = lname;
        lo.Salary__c = lSalary;
        lo.Account_Type__c = lacc;
        
        insert lo;
        
        pageReference p = new pageReference('/'+lo.id);
        return p;
        
    }
    
}