123/MyProject/src/objects/Motor_Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Agent_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agent ID</label>
        <referenceTo>Agent__c</referenceTo>
        <relationshipLabel>Motor Insurances</relationshipLabel>
        <relationshipName>Motor_Insurances</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manufactured_Year__c</fullName>
        <label>Manufactured Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Motor_Color__c</fullName>
        <label>Motor Color</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Motor_Type__c</fullName>
        <label>Motor Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Terms__c</fullName>
        <label>No. of Terms</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Policy_Holder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Policy Holder</label>
        <referenceTo>Policy_Holder__c</referenceTo>
        <relationshipLabel>Motor Insurances</relationshipLabel>
        <relationshipName>Motor_Insurances</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Premium_Amount__c</fullName>
        <label>Premium Amount</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Premium_End_Date__c</fullName>
        <label>Premium End  Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Premium_Start_Date__c</fullName>
        <label>Premium Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Premium_Type__c</fullName>
        <label>Premium Type</label>
        <picklist>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Motor Insurance</label>
    <nameField>
        <displayFormat>MIID-{0000}</displayFormat>
        <label>Policy ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Motor Insurances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

123/MyProject/src/objects/Policy_Holder__c.object
<CustomObject>
    <fields>
        <fullName>Agent_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent ID</label>
        <referenceTo>Agent__c</referenceTo>
        <relationshipLabel>Policy Holders</relationshipLabel>
        <relationshipName>Policy_Holders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Policy Holder</label>
    <nameField>
        <label>Policy Holder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Holders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

123/MyProject/src/classes/AddMotorInsurenceCtrl.cls
public class AddMotorInsurenceCtrl {
    public Motor_Insurance__c cds{get; set;}
        
    public Motor_Insurance__c setcds(Motor_Insurance__c op){
        this.cds=op;
        return cds;
    }
    public AddMotorInsurenceCtrl (ApexPages.StandardController controller) {
        cds=new Motor_Insurance__c();
    }

    public pagereference SaveandNew(){
        Motor_Insurance__c cd = new Motor_Insurance__c();
        cd.Policy_Holder__c= cds.Policy_Holder__c;
        cd.Agent_ID__c= cds.Agent_ID__c;
        cd.Motor_Type__c= cds.Motor_Type__c;
        cd.Motor_Color__c= cds.Motor_Color__c;
        cd.Manufactured_Year__c= cds.Manufactured_Year__c;
        cd.Premium_Amount__c= cds.Premium_Amount__c;
        cd.No_of_Terms__c= cds.No_of_Terms__c;
        cd.Premium_Type__c= cds.Premium_Type__c;
        cd.Premium_Start_Date__c= cds.Premium_Start_Date__c;
        cd.Premium_End_Date__c= cds.Premium_End_Date__c;

        insert cd;
        
        Pagereference pg = new Pagereference('/apex/AddMotorInsurenceVF');
        pg.setredirect(true);
        return pg;


    }
    public pageReference save(){
        Motor_Insurance__c cd = new Motor_Insurance__c();
        
        cd.Policy_Holder__c= cds.Policy_Holder__c;
        cd.Agent_ID__c= cds.Agent_ID__c;
        cd.Motor_Type__c= cds.Motor_Type__c;
        cd.Motor_Color__c= cds.Motor_Color__c;
        cd.Manufactured_Year__c= cds.Manufactured_Year__c;
        cd.Premium_Amount__c= cds.Premium_Amount__c;
        cd.No_of_Terms__c= cds.No_of_Terms__c;
        cd.Premium_Type__c= cds.Premium_Type__c;
        cd.Premium_Start_Date__c= cds.Premium_Start_Date__c;
        cd.Premium_End_Date__c= cds.Premium_End_Date__c;  
        
        insert cd;
        
        pagereference p = new pageReference('/'+cd.id);
        return p;
    
    }
    public PageReference Cancel(){
    
        pageReference g = new pageReference('/apex/IMSVF');
        
        return g;
    }
}