123/MyProject/src/objects/Policy_Holder__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Agent_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent ID</label>
        <referenceTo>Agent__c</referenceTo>
        <relationshipLabel>Policy Holders</relationshipLabel>
        <relationshipName>Policy_Holders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Income__c</fullName>
        <label>Income</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Policy Holder</label>
    <nameField>
        <label>Policy Holder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Holders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

123/MyProject/src/classes/AddPolicyHolderCtrl.cls
public class AddPolicyHolderCtrl {
    public Policy_Holder__c cds{get; set;}
        
    public Policy_Holder__c setcds(Policy_Holder__c op){
        this.cds=op;
        return cds;
    }
    public AddPolicyHolderCtrl(ApexPages.StandardController controller) {
        cds=new Policy_Holder__c();
    }

    public pagereference SaveandNew(){
        Policy_Holder__c cd = new Policy_Holder__c();
        cd.name = cds.name;
        cd.Date_of_Birth__c = cds.Date_of_Birth__c ;
        cd.Gender__c = cds.Gender__c;
        cd.Phone__c = cds.Phone__c;
        cd.Email__c = cds.Email__c;
        cd.Occupation__c= cds.Occupation__c;
        cd.Income__c= cds.Income__c;
        cd.Address__c = cds.Address__c;
        cd.Agent_ID__c = cds.Agent_ID__c;
        
        insert cd;
        
        Pagereference pg = new Pagereference('/apex/AddPolicyHolderVF');
        pg.setredirect(true);
        return pg;


    }
    public pageReference save(){
        Policy_Holder__c cd = new Policy_Holder__c();
        cd.name = cds.name;
        cd.Date_of_Birth__c = cds.Date_of_Birth__c ;
        cd.Gender__c = cds.Gender__c;
        cd.Phone__c = cds.Phone__c;
        cd.Email__c = cds.Email__c;
        cd.Occupation__c= cds.Occupation__c;
        cd.Income__c= cds.Income__c;
        cd.Address__c = cds.Address__c;
        cd.Agent_ID__c = cds.Agent_ID__c;
        
        insert cd;
        
        pagereference p = new pageReference('/'+cd.id);
        return p;
    
    }
    public PageReference Cancel(){
    
        pageReference g = new pageReference('/apex/IMSVF');
        
        return g;
    }
}